# Generated by Django 3.1.5 on 2021-01-24 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, unique=True)),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('lon', models.FloatField(blank=True, default=None, null=True)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, default=None, null=True)),
                ('feels_like', models.FloatField(blank=True, default=None, null=True)),
                ('humidity', models.IntegerField(blank=True, default=None, null=True)),
                ('message', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.zipcode')),
            ],
        ),
    ]
